sudo: true
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - .cpcache
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
  - chmod +x linux-install-1.9.0.375.sh
  - sudo ./linux-install-1.9.0.375.sh
script:
  - mkdir gh-pages
  - clojure build.clj -a > gh-pages/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: gh-pages
  target-branch: gh-pages
  on:
    branch: master
